routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\ForgetController;
use App\Http\Controllers\Auth\ResetController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\PasswordController;

Route::get("/", function () {
    return "Home Page";
})->name("home");

Route::name("auth.")
    ->middleware('auth.guest')
    ->prefix("auth")->group(function () {
        Route::get("register", [RegisterController::class, 'register'])->name("register");
        Route::post("register", [RegisterController::class, 'store'])->name("store");
        Route::get("login", [LoginController::class, 'login'])->name("login");
        Route::post("login", [LoginController::class, 'check'])->name("check");
        Route::get("forget", [ForgetController::class, 'forget'])->name("forget");
        Route::post("forget", [ForgetController::class, 'resetLink'])->name("reset.link");
        Route::get("reset", [ResetController::class, 'reset'])->name("reset");
        Route::post("reset", [ResetController::class, 'set'])->name("reset.password");
    });

Route::name("admin.")
    ->middleware("auth.guard")
    ->prefix("admin")
    ->group(function () {
        Route::get("/", [HomeController::class, "index"])->name("home");
        Route::get("/auth/user", [ProfileController::class, "show"])->name("logged.user");
        Route::get("/profile", [ProfileController::class, "index"])->name("profile");
        Route::put("/profile", [ProfileController::class, "update"])->name("profile.update");
        Route::get("/change-password", [PasswordController::class, "index"])->name("change.password");
        Route::post("/logout", [HomeController::class, "logout"])->name("logout");
    });

app/Models/ForgetPassword.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ForgetPassword extends Model
{
    use HasFactory;

    const UPDATED_AT = null;

    protected $fillable = ['token'];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        "firstname",
        "lastname",
        "nicename",
        "email",
        "slug",
        "email_verified_key",
        "email_verified_at",
        "remember_token",
        "password",
        "status",
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function setEmailAttribute($value)
    {
        if (!empty($value))
            $this->attributes['email'] = strtolower($value);
    }

    public function setPasswordAttribute($value)
    {
        if (!empty($value))
            $this->attributes['password'] = bcrypt($value);
    }

    public function meta()
    {
        return $this->hasMany(Usermeta::class, 'user_id');
    }

    public function forgetPassword()
    {
        return $this->hasOne(ForgetPassword::class, 'user_id');
    }
}

app/Models/Usermeta.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Usermeta extends Model
{
    use HasFactory;

    protected $fillable = [
        "meta_key",
        "meta_value",
    ];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

}

app/Http/Controllers/Admin/HomeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index()
    {
        return view("admin.home");
    }

    public function logout()
    {
        auth()->logout();
        return response()->json([
            'next' => route("auth.login")
        ], 200);
    }
}

app/Http/Controllers/Admin/PasswordController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class PasswordController extends Controller
{
    public function index()
    {
        return view("admin.change-password");
    }
}

app/Http/Controllers/Admin/ProfileController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\AdminProfileRequest;
use Illuminate\Http\Request;

class ProfileController extends Controller
{
    public function index()
    {
        return view('admin.profile');
    }

    public function show()
    {
        $user = auth()->user();
        return response()->json(['user' => $user]);
    }

    public function update(AdminProfileRequest $request)
    {
        $user = auth()->user();
        $user->update($request->only('firstname'));
        return response()->json(['user' => $user, 'message' => 'User profile details updated successfully!'], 200);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Support\Facades\DB;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/admin/change-password.blade.php
@extends("layouts.admin.main")

resources/views/admin/home.blade.php
@extends("layouts.admin.main")

resources/views/admin/profile.blade.php
@extends("layouts.admin.main")
@section('title')
    <title>Account Settings</title>
@endsection
@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md"></div>
            <div class="col-md-9 my-5">
                <div class="card p-4">
                    <div class="card-body">
                        <h4 class="text-muted">
                            <span class="right-underline-title">Account Settings</span>
                        </h4>
                        <p class="text-sm text-muted mt-3">
                            Edit your personal contact information.
                            <b>Please ensure all information is correct and accurate. This information is for internal
                                use only and will not be visible on verification pages.</b>
                        </p>
                        <hr>
                        <div class="row">
                            <div class="col-md-12">
                                <label>Account Information</label>
                            </div>
                        </div>
                        <v-form action="{{route("admin.profile.update")}}"
                                method="put"
                                clear="false"
                                :data="userDetails">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <v-input
                                            :form="userDetails"
                                            field="firstname"
                                            label="First Name"
                                            class="form-control"
                                            autofocus="true"
                                            autocomplete="false"
                                            placeholder="Enter firstname"/>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <v-input
                                            :form="userDetails"
                                            field="lastname"
                                            label="Last Name"
                                            class="form-control"
                                            placeholder="Enter lastname"/>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <v-input
                                            :form="userDetails"
                                            field="email"
                                            label="Email"
                                            class="form-control"
                                            placeholder="Enter email"/>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <v-input
                                            :form="userDetails"
                                            field="slug"
                                            label="Username"
                                            class="form-control"
                                            placeholder="Enter username"/>
                                    </div>
                                </div>
                            </div>
                            <v-alert :form="userDetails"></v-alert>
                            <div class="row">
                                <div class="col-12">
                                    <v-submit
                                        :form="userDetails"
                                        class="btn btn-primary btn-flat">
                                        Update
                                    </v-submit>
                                </div>
                            </div>
                        </v-form>
                    </div>
                </div>
            </div>
            <div class="col-md"></div>
        </div>
    </div>
@endsection
@section('js')
    <script !src="">
        vue_app.mixin({
            data() {
                return {
                    userDetails: new vForm({
                        firstname: null,
                        lastname: null,
                        email: null,
                        slug: null
                    }, [], false),
                }
            },
            watch: {
                userDetails: {
                    handler: function (value, oldValue) {
                        let response = value.server_response;
                        if (response.user) {
                            this.auth_user = response.user;
                        }
                    },
                    deep: true
                }
            },
            mounted: async function () {
                await this.getProfileDetails();
            },
            methods: {
                getProfileDetails: async function () {
                    try {
                        const response = await axios.get(`{{route('admin.logged.user')}}`);
                        this.userDetails.setData(response.data.user);
                    } catch (e) {
                        console.log(e.response);
                    }
                }
            }
        });
    </script>
@endsection

resources/views/layouts/admin/header.blade.php
<nav class="main-header navbar navbar-expand border-bottom-0 navbar-light navbar-white">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link"
               data-widget="pushmenu"
               href="JavaScript:void(0)"
               role="button"><i class="fas fa-bars"></i></a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            @{{ auth_user.firstname ?? null }}
            <button type="button"
                    :disabled="logout_busy"
                    @click="doLogout"
                    class="btn btn-sm btn-flat btn-outline-danger">
                @{{ logout_busy?"Signing Out...":"Logout" }}
            </button>
        </li>
    </ul>
</nav>

resources/views/layouts/admin/main.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible"
          content="ie=edge">
    <link rel="icon"
          href="{{asset('imgs/favicon.png')}}">
    @yield('meta')
    @yield('title')
    <link rel="stylesheet"
          href="{{asset('css/app.css')}}">
    <link rel="stylesheet"
          href="{{asset('css/admin-lte.css')}}">
    @yield('css')
</head>
<body class="sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed accent-teal"
      style="height: auto;">
<div class="wrapper"
     id="vue-app"
     style="visibility: hidden;">
    @include('layouts.admin.header')
    @include('layouts.admin.sidebar')
    <div class="content-wrapper">
        <div class="hd-fixed-wrapper">
            @yield('content')
        </div>
    </div>
    @include('layouts.admin.footer')
</div>
<script src="{{asset('js/app.js')}}"></script>
<script src="{{asset('js/admin-lte.js')}}"></script>
<script src="{{asset('js/vue.js')}}"></script>
@yield('js')
<script !src="">

    vue_app.mixin({
        data: function () {
            return {
                logout_busy: false
            }
        },
        mounted: async function () {
            await this.getUserDetails();
        },
        methods: {
            doLogout: async function () {
                this.logout_busy = true;

                this.logout_busy = false;

            },
            getUserDetails: async function () {
                const response = await axios.get(`{{route('admin.logged.user')}}`);
                this.auth_user = response.data.user;
            }
        }
    });

    if (vue_app)
        vue_app.mount("#vue-app");
</script>
</body>
</html>

resources/views/layouts/admin/sidebar.blade.php
<aside class="main-sidebar sidebar-light-primary">
    <a href="{{route("admin.home")}}"
       class="brand-link navbar-white text-center">
        <img style="width: 65px;max-height: 40px;"
             src="{{asset('imgs/favicon.png')}}"
             alt="{{env("APP_NAME", "")}}">
    </a>
    <div class="sidebar">
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column nav-flat nav-legacy"
                data-widget="treeview"
                role="menu"
                data-accordion="false">
                <li class="nav-item">
                    <a href="{{route("admin.home")}}"
                       class="nav-link {{in_array(request()->route()->getName(), ['admin.home'])?"active":null}}">
                        <i class="nav-icon fas fa-chart-line"></i>
                        <p>
                            Dashboard
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route("admin.profile")}}"
                       class="nav-link {{in_array(request()->route()->getName(), ['admin.profile'])?"active":null}}">
                        <i class="nav-icon fas fa-user"></i>
                        <p>
                            Profile
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route("admin.change.password")}}"
                       class="nav-link {{in_array(request()->route()->getName(), ['admin.change.password'])?"active":null}}">
                        <i class="nav-icon fas fa-lock"></i>
                        <p>
                            Change Password
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</aside>

resources/views/layouts/frontend/footer.blade.php
Footer

resources/views/layouts/frontend/header.blade.php
Header

resources/views/layouts/frontend/main.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1">
    @yield('meta')
    <link rel="icon"
          href="{{asset('imgs/favicon.png')}}">
    <title>
        @yield('title')
    </title>
    <link rel="stylesheet"
          href="{{asset('css/app.css')}}">
    @yield('css')
</head>
<body>
@include('layouts.frontend.header')
@yield('content')
@include('layouts.frontend.footer')
<script src="{{asset('js/app.js')}}"></script>
@yield('js')
</body>
</html>